import { JoditConfig } from "../common/types/jodit.types";

export const defaultJoditConfig: JoditConfig = {
  height: 600,
  minHeight: 400,
  maxHeight: 800,
  placeholder:
    "Write your amazing blog content here... Start with a captivating introduction!",
  readonly: false,
  toolbar: true,
  toolbarButtonSize: "middle",
  buttons: [
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "|",
    "ul",
    "ol",
    "|",
    "outdent",
    "indent",
    "|",
    "font",
    "fontsize",
    "brush",
    "paragraph",
    "|",
    "left",
    "center",
    "right",
    "justify",
    "|",
    "image",
    "video",
    "file",
    "|",
    "table",
    "|",
    "link",
    "|",
    "hr",
    "blockquote",
    "|",
    "source",
    "preview",
    "|",
    "cut",
    "copy",
    "paste",
    "copyformat",
    "|",
    "superscript",
    "subscript",
    "|",
    "symbols",
    "|",
    "undo",
    "redo",
    "|",
    "fullsize",
    "about",
    "find",
    "selectall",
    "print",
    "eraser",
  ],
  toolbarAdaptive: false,
  enter: "div",
  allowTabNavigation: true,
  saveSelectionOnBlur: true,
  preserveSelection: true,
  showXPathInStatusbar: false,
  showCharsCounter: true,
  showWordsCounter: true,
  showPlaceholder: true,
  useSearch: true,
  spellcheck: true,
  iframe: false,
  autofocus: false,
  direction: "ltr",
  disablePlugins: ["mobile", "speechRecognize"],
  style: {
    fontSize: "16px",
    lineHeight: "1.6",
    fontFamily: "Arial, sans-serif",
  },
  uploader: {
    insertImageAsBase64URI: true,
  },
  link: {
    noFollowCheckbox: true,
    openInNewTabCheckbox: true,
  },
  image: {
    editSrc: true,
    useImageEditor: true,
  },
};

export const faqJoditConfig: JoditConfig = {
  height: 300,
  minHeight: 200,
  maxHeight: 200,
  placeholder:
    "Write your amazing blog content here... Start with a captivating introduction!",
  readonly: false,
  toolbar: true,
  toolbarButtonSize: "middle",
  buttons: [
    "bold",
    "italic",
    "underline",
    "|",
    "outdent",
    "indent",
    "|",
    "font",
    "fontsize",
    "brush",
    "paragraph",
    "|",
    "left",
    "center",
    "right",
    "justify",
    "|",

    "|",
    "link",
    "|",
    "hr",
    "blockquote",
  
    "|",
    "cut",
    "copy",
    "paste",
  ],
  toolbarAdaptive: false,
  enter: "div",
  allowTabNavigation: true,
  saveSelectionOnBlur: true,
  preserveSelection: true,
  showXPathInStatusbar: false,
  showCharsCounter: true,
  showWordsCounter: true,
  showPlaceholder: true,
  useSearch: true,
  spellcheck: true,
  iframe: false,
  autofocus: false,
  direction: "ltr",
  disablePlugins: ["mobile", "speechRecognize"],
  style: {
    fontSize: "16px",
    lineHeight: "1.6",
    fontFamily: "Arial, sans-serif",
  },
  uploader: {
    insertImageAsBase64URI: true,
  },
  link: {
    noFollowCheckbox: true,
    openInNewTabCheckbox: true,
  },
  image: {
    editSrc: true,
    useImageEditor: true,
  },
};
